version: 2
jobs:
  build: 
    working_directory: ~/app
    docker:
      - image: circleci/android:api-26-node8-alpha
    environment:
      TOOL_NODE_FLAGS: --max-old-space-size=8192
    steps:
      - checkout
      - run:
          name: install Meteor
          # only install meteor if bin isn't found
          command: command -v meteor >/dev/null 2>&1 || curl https://install.meteor.com/ | /bin/sh 
      - run:
          name: install Gradle
          command: sudo apt-get install gradle
      - run:
          name: check versions
          command: |
            echo "Meteor version:"
            # this forces Meteor to download whatever release your project is using
            meteor --version
            which meteor
            echo "Meteor node version:"
            meteor node -v
            echo "Meteor npm version:"
            meteor npm -v
      - run:
          name: install npm packages
          command: meteor npm install
      - run:
          name: Build Meteor
          command: |
            meteor build --directory .build --architecture os.linux.x86_64 --server https://pos.mrwinston.nl
      - persist_to_workspace:
          root: ~/app
          paths:
            - node_modules
            - .build
  android:
    working_directory: ~/app
    docker:
      - image: circleci/android:api-26-node8-alpha
    steps:
      - checkout:
          path: ~/app
      - attach_workspace:
          at: ~/app
      - run:
          name: install Ruby
          command: sudo apt-get install ruby2.3-dev && sudo apt-get install rubygems
      - run:
          name: Build Meteor (Android)
          command: |
            pwd     

            sudo gem install fastlane
            sudo gem install -n /usr/local/bin bundler -v 1.12
            # sudo gem install bundler

            echo 'export PATH="$HOME/.fastlane/bin:$PATH"' >> ~/.bash_profile
            
            bundle install
            ls -la
            pwd
            git clone git@bitbucket.org:possys/certs.git .certs
            bundle exec fastlane android beta
  ios:
    macos:
      xcode: "9.0"
    shell: /bin/bash --login -o pipefail
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    steps:
      - checkout:
          path: ~/app
      - run:
          name: Set Ruby Version
          command:  echo "ruby-2.4" > ~/.ruby-version
      - run:
          name: Build Meteor (IOS)
          command: |
            # if [ "${CIRCLE_BRANCH}" == "master" ]; then
                        ./gradlew wrapper --gradle-version 2.12

              sudo gem install fastlane -NV
              sudo gem install bundler

              echo 'export PATH="$HOME/.fastlane/bin:$PATH"' >> ~/.bash_profile
              bundle install
              # bundle exec fastlane ios beta
            # fi
workflows:
  version: 2
  node-android-ios:
    jobs:
      - build
      - android:
          requires:
            - build
      - ios:
          requires:
            - build