version: 2
jobs:
  build: 
    macos:
      xcode: "9.2.0"
    working_directory: ~/app
    environment:
      TOOL_NODE_FLAGS: --max-old-space-size=8192
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      ANDROID_HOME: "/usr/local/share/android-sdk"
      ANDROID_SDK_HOME: "/usr/local/share/android-sdk"
      ANDROID_SDK_ROOT: "/usr/local/share/android-sdk"
    steps:
      - checkout
      - run:
          name: Set Ruby Version
          command: echo "ruby-2.3" > ~/.ruby-version
      - run:
          name: install android sdk
          command: |
            brew tap caskroom/cask
            brew tap caskroom/versions
            brew cask install android-sdk
            brew install gradle
            #export PATH="$PATH:/usr/local/share/android-sdk/tools"
      - run:
          name: update android sdk
          command: |
            echo "y" | sdkmanager "build-tools;25.0.1"
            echo "y" | sdkmanager "platforms;android-25"
      - run:
          name: install Meteor
          # only install meteor if bin isn't found
          command: command -v meteor >/dev/null 2>&1 || curl https://install.meteor.com/ | /bin/sh 
      - run:
          name: check versions
          command: |
            echo "Meteor version:"
            # this forces Meteor to download whatever release your project is using
            meteor --version
            which meteor
            echo "Meteor node version:"
            meteor node -v
            echo "Meteor npm version:"
            meteor npm -v
      - run:
          name: install npm packages
          command: meteor npm install
      - run:
          name: Build Meteor
          command: |
            source ~/.bash_profile
            pwd
            meteor build --directory .build --architecture os.linux.x86_64 --server https://pos.mrwinston.nl
      - run:
          name: Build Meteor (IOS)
          command: |
            # if [ "${CIRCLE_BRANCH}" == "master" ]; then
              sudo gem install fastlane -NV
              sudo gem install bundler

              echo 'export PATH="$HOME/.fastlane/bin:$PATH"' >> ~/.bash_profile
              bundle install
              # bundle exec fastlane ios beta
            # fi
      - run:
          name: Build Meteor (Android)
          command: |
            pwd     
            git clone git@bitbucket.org:possys/certs.git .certs
            bundle exec fastlane android beta
            
