version: 2
jobs:
  build: 
    macos:
      xcode: "9.2.0"
    working_directory: ~/app
    environment:
      TOOL_NODE_FLAGS: --max-old-space-size=8192
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
    steps:
      - checkout
      - run:
          name: Set Ruby Version
          command: echo "ruby-2.3" > ~/.ruby-version
      - run:
          name: install android sdk
          command: |
            brew tap caskroom/cask
            brew tap caskroom/versions
            brew cask install android-sdk
            brew install gradle
            brew install bundler
            brew cask install fastlane
            echo 'export PATH="$HOME/.fastlane/bin/fastlane_lib:$PATH"' >> ~/.bash_profile
            echo 'export PATH="$HOME/.fastlane/bin:$PATH"' >> ~/.bash_profile
            echo 'export ANDROID_HOME=/usr/local/share/android-sdk'
            echo 'export PATH=$PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools' >> ~/.bash_profile
      - run:
          name: update android sdk
          command: |
            echo "y" | sdkmanager "build-tools;27.0.3"
            echo "y" | sdkmanager "platforms;android-26"
      - run:
          name: install Meteor
          # only install meteor if bin isn't found
          command: command -v meteor >/dev/null 2>&1 || curl https://install.meteor.com/ | /bin/sh 
      - run:
          name: check versions
          command: |
            echo "Meteor version:"
            # this forces Meteor to download whatever release your project is using
            meteor --version
            which meteor
            echo "Meteor node version:"
            meteor node -v
            echo "Meteor npm version:"
            meteor npm -v
            echo "Gradle version:"
            gradle -v
      - run:
          name: install npm packages
          command: meteor npm install
      - run:
          name: Build Meteor
          command: meteor build --directory .build --architecture os.linux.x86_64 --server https://pos.mrwinston.nl
      - run:
          name: Build Meteor (Android)
          command: |
            git clone git@bitbucket.org:possys/certs.git .certs
            bundle install
            bundle exec fastlane android beta
      - run:
          name: Build Meteor (IOS)
          command: |
            bundle install
            bundle exec fastlane ios beta
            
